/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as ShellLayoutRouteImport } from './pages/_shell/layout'
import { Route as SessionRouteImport } from './pages/session'
import { Route as ShellIndexRouteImport } from './pages/_shell/index'
import { Route as ShellComponentsRouteImport } from './pages/_shell/components'

const ShellLayoutRoute = ShellLayoutRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionRoute = SessionRouteImport.update({
  id: '/session',
  path: '/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellIndexRoute = ShellIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellLayoutRoute,
} as any)
const ShellComponentsRoute = ShellComponentsRouteImport.update({
  id: '/components',
  path: '/components',
  getParentRoute: () => ShellLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ShellIndexRoute
  '/session': typeof SessionRoute
  '/components': typeof ShellComponentsRoute
}
export interface FileRoutesByTo {
  '/session': typeof SessionRoute
  '/components': typeof ShellComponentsRoute
  '/': typeof ShellIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_shell': typeof ShellLayoutRouteWithChildren
  '/session': typeof SessionRoute
  '/_shell/components': typeof ShellComponentsRoute
  '/_shell/': typeof ShellIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/session' | '/components'
  fileRoutesByTo: FileRoutesByTo
  to: '/session' | '/components' | '/'
  id: '__root__' | '/_shell' | '/session' | '/_shell/components' | '/_shell/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ShellLayoutRoute: typeof ShellLayoutRouteWithChildren
  SessionRoute: typeof SessionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session': {
      id: '/session'
      path: '/session'
      fullPath: '/session'
      preLoaderRoute: typeof SessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/': {
      id: '/_shell/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ShellIndexRouteImport
      parentRoute: typeof ShellLayoutRoute
    }
    '/_shell/components': {
      id: '/_shell/components'
      path: '/components'
      fullPath: '/components'
      preLoaderRoute: typeof ShellComponentsRouteImport
      parentRoute: typeof ShellLayoutRoute
    }
  }
}

interface ShellLayoutRouteChildren {
  ShellComponentsRoute: typeof ShellComponentsRoute
  ShellIndexRoute: typeof ShellIndexRoute
}

const ShellLayoutRouteChildren: ShellLayoutRouteChildren = {
  ShellComponentsRoute: ShellComponentsRoute,
  ShellIndexRoute: ShellIndexRoute,
}

const ShellLayoutRouteWithChildren = ShellLayoutRoute._addFileChildren(
  ShellLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ShellLayoutRoute: ShellLayoutRouteWithChildren,
  SessionRoute: SessionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
